### ISSUE TITLE
C092: fix remaining formatting issues

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#950]

**Comment by sergei-kalugin** [comment]
@ashleycole26, I fixed the line and the footnotes for the problematic citation in C092 _Shipwrecks and Civil War_.

Could you please go over one more time and see if the rest is ok?

I noticed that there is a `ref` tag used for a link (line 50). That should be converted to an `<a>` tag (see the manual [here](https://github.com/MADStudioNU/the-pulter-project/wiki/Linking-to-TPP-Resources#from-a-connection)).

I would also double check that the footnote references and corresponding notes behave correctly when clicked.

**Comment by ashleycole26** [comment]
Thank you for catching Line 50, that wasn't supposed to be linked at all
actually. I removed it. I still see a bullet point in front of that latin
phrase in Line 150.

Ashley

**Comment by sergei-kalugin** [comment]
It might help to clear the browser's cache.

**Comment by ashleycole26** [comment]
yes, great, thank you!
